# Generated by Django 3.0.6 on 2020-05-29 21:02

from django.db import migrations


def create_data(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    Customer(first_name="Customer 001",
             last_name="Customer 001",
             email="customer001@email.com",
             phone="00000001",
             address="Customer 001 Address",
             description="Customer 002 description").save()
    Customer(first_name="Customer 002",
             last_name="Customer 002",
             email="customer002@email.com",
             phone="00000002",
             address="Customer 002 Address",
             description="Customer 002 description").save()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
